### ISSUE TITLE
I would like the instructions for extractor development to be in a useful place 

### ISSUE THREAD

**Issue by dlebauer** [AgPipeline/computing-pipeline#1]
Currently the process for extractor dev is here https://docs.terraref.org/developer-manual/developing-clowder-extractors

It includes a standard structure for documenting individual extractors in a readme - this can be a template in the extractor templates. There is lots of other stuff to review and delete, modify, and put somewhere.

Please update and incorporate into agpipeline docs / wiki etc.

**Comment by Chris-Schnaufer** [comment]
Placing technical documentation onto AgPipeline organization GitHub site

**Comment by Chris-Schnaufer** [comment]
Pull requests:
* main documentation: https://github.com/AgPipeline/AgPipeline.github.io/pull/1
* supporting template: https://github.com/AgPipeline/computing-pipeline/pull/31
