### ISSUE TITLE
Add more space to Welsch database backup volume

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#105]
Due to leap year and addition of data, the available space should be doubled

**Comment by dlebauer** [comment]
create copy of vol
create new vol using saved image
swap out

**Comment by julianpistorius** [comment]
This might also be useful:

https://computingforgeeks.com/how-to-resize-extend-cinder-volume-in-openstack/

**Comment by Chris-Schnaufer** [comment]
Waiting on a response from CyVerse re: who is handling Welsch on Open Stack now
