### ISSUE TITLE
Update Select Transformers to use new Metadata Override flag

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#108]
Follow up on issue #80

The following transformers can be updated to use the new Metadata Override flag to suppress the need for metadata:

- [ ] transformer-geostream-csvupload
- [ ] transformer-irrigation_datparser
- [ ] transformer-weather_datparser
- [ ] transformer-envlog2netcdf
- [ ] transformer-betydb-csvupload

Create new Docker images & push to DockerHub

**Comment by dlebauer** [comment]
Can this be closed?

**Comment by Chris-Schnaufer** [comment]
Closing as no longer relevant
