### ISSUE TITLE
Design data transfer client

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/computing-pipeline#111]
**Task to do**

- Design the client that gets the data from the gantry and writes it into IRODS

**Reason**

- Need to get the data from the gantry to the CyVerse Data Store in a timely & reliable manner

**Result**

- A plan that is implementable

**TODO: Steps to take**

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

**Comment by julianpistorius** [comment]
Related:

- https://github.com/AgPipeline/issues-and-projects/issues/93
- https://github.com/az-digitalag/organization/issues/177

**Comment by julianpistorius** [comment]
## Notes:

### Fast Data Transfer:

- https://fast-data-transfer.github.io/
- https://github.com/fast-data-transfer


### Syncthing:

- https://syncthing.net/
- https://docs.syncthing.net/dev/rest.html
- https://docs.syncthing.net/dev/events.html
- https://docs.syncthing.net/advanced/folder-ignoredelete.html
- https://www.gigenet.com/blog/how-to-set-up-a-complex-syncthing-network/

**Comment by julianpistorius** [comment]
Still relevant @dlebauer?

**Comment by dlebauer** [comment]
no - I tagged a bunch of issues like this with ua-gantry and put them in the icebox. I'll close them next time I go through the backlog.
