### ISSUE TITLE
use scan log to ascertain scan completion

### ISSUE THREAD

**Issue by dlebauer** [AgPipeline/computing-pipeline#120]
Jeffrey has a scan log CSV file that could be pushed to the gantry cache server via FTP.

Replaces https://github.com/az-digitalag/organization/issues/177 which was originally posted by @julianpistorius in https://github.com/az-digitalag/organization/pull/170

**Comment by julianpistorius** [comment]
@dlebauer still relevant?

**Comment by dlebauer** [comment]
No
