### ISSUE TITLE
Direct users to drone pipeline home page

### ISSUE THREAD

**Issue by KristinaRiemer** [AgPipeline/computing-pipeline#121]
Do this by adding [link to home page on OSF](https://osf.io/xdkcy/wiki/home/) along with text that says "Start here" to all relevant pages where users could start first (GH repos, website, other pipelines' docs). Will probably need to get Chris' help with this due to permissions.

**Comment by MagicMilly** [comment]
After meeting with Chris, he added a link to the OSF page from the `drone-pipeline-environment` repo, and there is also a link to OSF from the main github page. As part of our OLS project going forward, we'll add more specific prerequisites to the OSF page.
