### ISSUE TITLE
Update canopy cover transformer for gantry pipeline

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#129]
**Task to do**
Build, test, and deploy new gantry canopy cover transformer

**Reason**
The canopy cover algorithm has been updated

**Result**
A new canopy cover transformer is available for gantry pipeline

**Comment by Chris-Schnaufer** [comment]
Using the `develop` branch of the [gantry canopy cover repository](https://github.com/AgPipeline/transformer-canopycover) to get the updated algorithm:
1) Build a new Docker image
2) Get the test images from https://drive.google.com/open?id=1T7kFi1U8wzJDxDMp2UHnpPQYr4kqnmR7
3) Use one or more of the test images to calculate the new canopy cover (see https://github.com/AgPipeline/transformer-canopycover README for instructions, substituting image & file names as needed)
4) Check that CSV files are created and that they contain reasonable values
5) If code changed, create a new branch, checkin changes, create a pull request to merge into the `develop` branch

**Comment by Chris-Schnaufer** [comment]
https://github.com/AgPipeline/transformer-canopycover/pull/9

**Comment by dlebauer** [comment]
Resolved by https://github.com/AgPipeline/transformer-canopycover/pull/9
