### ISSUE TITLE
Review David's README pull requests

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#135]
**Task to do**
Review the README.md Pull Requests: https://github.com/AgPipeline/transformer-soilmask/blob/update-readme/README.md and https://github.com/AgPipeline/transformer-canopycover/pull/6

**Reason**
Review the pull requests

**Result**
Better & approved README.md files

**Comment by Chris-Schnaufer** [comment]
@jvanderleeuw What's the status of this?

**Comment by jvanderleeuw** [comment]
It should be good; I talked with David the week before last and there were no large changes that needed to be made; I'll make sure with David today

**Comment by dlebauer** [comment]
merged PR
