### ISSUE TITLE
Implement pylint GitHub workflow for Drone repos

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#143]
**Task to do**
Implement pylint GitHub workflow for Drone repos

**Reason**
Part of Continuous Integration

**Result**
Pull Requests and pushes to `master` and `develop` will be automatically pylint checked using a standard

**Comment by dlebauer** [comment]
Would be nice to also document this + 
* [x] instructions on how to run pylint before submitting a PR?
   * @kyclark also recommended asking users to apply an auto-formatter like yapf or black
* [x] create issues to implement for pecanproject/BETYdb-YABA and terraref/brapi

There appear to be a few nice options here: https://github.com/marketplace?type=actions&query=pylint

**Comment by Chris-Schnaufer** [comment]
The problem I see with GitHub and code formatters is that the code formatters would need to checkin changes, which opens the door to potential problems.

I think that people should be able to use whatever code formatter they want. Pylint would be the final arbiter on whether the code can be considered "correct".

Something between having nothing and auto-code-checking, would be to recommend a code formatter that people use

**Comment by Chris-Schnaufer** [comment]
Lots of PRs outstanding: each repo that has the "drone" topic has a PR against it for a pylint workflow

**Comment by Chris-Schnaufer** [comment]
New ticket for making a change David suggested to move top-level into .github folder
