### ISSUE TITLE
Fill in README for canopy cover transformer

### ISSUE THREAD

**Issue by dlebauer** [AgPipeline/computing-pipeline#144]
**Documentation Request Type**

The README for the instructions for building, testing, and deploying the canopy cover transformer should be filled in.

(replaces https://github.com/terraref/tutorials/issues/243)

**Comment by Chris-Schnaufer** [comment]
Look at https://github.com/AgPipeline/issues-and-projects/issues/90 for additional details.

**Comment by jvanderleeuw** [comment]
PR: https://github.com/AgPipeline/transformer-canopycover/pull/11

Issue resolved by adding description of how to test and deploy the transformer as well as linking sample plot images to the README
