### ISSUE TITLE
Migrate SQLite DB generating script to TERRAREF Workbench environment

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#146]
**Task to do**
The SQLite script at https://github.com/Chris-Schnaufer/generate_sqlite (might have been moved to AgPipeline organization) needs to be modified to access TERRAREF provided local storage. This can happen with TERRAREF Workbench access.

**Reason**
Globus times out frequently preventing a full run of a season's data. Direct disk access will avoid this problem.

**Result**
The script can run with Globus or local access to necessary files

Refer to: https://app.zenhub.com/workspaces/ua-ag-data-science-5a57a3198339f11ba1c85775/issues/terraref/data-paper/20

**Comment by dlebauer** [comment]
@Chris-Schnaufer your credentials for the workbench are in stache.arizona.edu

**Comment by Chris-Schnaufer** [comment]
Currently waiting for terraref workbench gateway error to be resolved.

**Comment by Chris-Schnaufer** [comment]
Previous issue is resolved. It keeps running into issues when trying to work on an entire season's worth of data. Making another attempt and then will try breaking the season into monthly chunks, and then weekly if monthly chunks fail

**Comment by Chris-Schnaufer** [comment]
Follow on issue: https://app.zenhub.com/workspaces/ua-ag-data-science-5a57a3198339f11ba1c85775/issues/agpipeline/issues-and-projects/173
