### ISSUE TITLE
Architecture discussion - Part 1

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/computing-pipeline#148]
Notes: https://hackmd.io/KJ2bgG9_RRCY3jr8jCRlsw

**Comment by dlebauer** [comment]
Please define actionable item here - 5 points seems like a lot! How do we know if it is done? 

Is this related to related to agpipeline/drone-pipeline-environment#40?

**Comment by julianpistorius** [comment]
> 5 points seems like a lot
> How do we know if it is done?
> Is this related to related to...

Exactly. I don't know. That's why I wanted you to set boundaries on time and scope as I mentioned in the Slack thread. The points are a reflection of my uncertainty around time and scope.
