### ISSUE TITLE
Identify post-OLS followup steps

### ISSUE THREAD

**Issue by KristinaRiemer** [AgPipeline/computing-pipeline#151]
**Action Items for OLS Project**
- [ ] Review more specific prerequisites with Chris to add to OSF page
- [ ] Identify and document next steps
- [x] Put presentation in group repo
- [x] Write and publish blog post about program

**Comment by MagicMilly** [comment]
Because we're still working on goals and action items following #ShutDownSTEM for writing hour, this will be bumped to next Sprint.

**Comment by MagicMilly** [comment]
Moving this again - need to schedule a meeting with @KristinaRiemer to start making progress

**Comment by KristinaRiemer** [comment]
See [group website ticket](https://github.com/az-digitalag/organization/issues/185) and [Emily's OSF investigations](https://github.com/az-digitalag/organization/issues/249) for more followup.
