### ISSUE TITLE
Merge transformer-rgb-indices (Greenness RGB transformer) develop branch to master branch

### ISSUE THREAD

**Issue by jvanderleeuw** [AgPipeline/computing-pipeline#154]
Merge develop branch of [transformer-rgb-indices](https://github.com/AgPipeline/transformer-rgb-indices/tree/develop) into master branch and make sure that the coding style guide is followed.

**Comment by Chris-Schnaufer** [comment]
Merged

**Comment by dlebauer** [comment]
@Chris-Schnaufer  which branch was merged? we can't find the particular commit that this is referring to

**Comment by Chris-Schnaufer** [comment]
I think I started doing this and didn't finish. It's done now

https://github.com/AgPipeline/transformer-rgb-indices/pull/2
