### ISSUE TITLE
Decide which transformer_class functions are needed in an installable library

### ISSUE THREAD

**Issue by jvanderleeuw** [AgPipeline/computing-pipeline#156]
The installable library which was recently created contains a transformer_class.py file derived from base-transformer-class. This file contains functions that are different from those in the transformer_class.py file within opendronemap. The goal is to see which functions are needed.

**Functions in Question**

In [transformer-opendronemap](https://github.com/AgPipeline/transformer-opendronemap/blob/pylint_file_move/transformer_class.py):

* supported_file_exts
* get_acceptable_files

In [agpypeline](https://github.com/AgPipeline/agpypeline/blob/remove_dependencies/agpypeline/transformer_class.py):

* convert_and_clean_tag
* default_epsg
* get_image_file_epsg
* get_image_file_geobounds
* generate_transformer_md

**Comment by Chris-Schnaufer** [comment]
The open drone map functions in question should either be added to the library and/or the library changed to make those calls when needed.

**Comment by Chris-Schnaufer** [comment]
@jvanderleeuw Can you look over this ticket and see what's still relevant and update this issue?

**Comment by jvanderleeuw** [comment]
Both the [transformer-opendronemap](https://github.com/AgPipeline/transformer-opendronemap/tree/develop) and the [agpypeline](https://github.com/AgPipeline/agpypeline/tree/develop) libraries were changed when the scif workflow was implemented and variable/function names were changed

supported_file_exts became KNOWN_IMAGE_FILE_EXTS
get_acceptable_files became check_for_image_file
convert_and_clean_tag stayed
default_epsg became a parameter
get_image_file_epsg became get_epsg
get_image_file_geobounds became image_get_geobounds
generate_transformer_md stayed
