### ISSUE TITLE
Recommend framework for unit and integration testing for agpipeline

### ISSUE THREAD

**Issue by dlebauer** [AgPipeline/computing-pipeline#157]
We are starting to make use of GitHub workflows and Actions for automated code testing. We are migrating from TravisCI to GitHub Actions.

TODO:

* [x] survey of currently available Python 3.7+ testing tools 
* [x] review  [drone-pipeline-environment master branch](https://github.com/AgPipeline/drone-pipeline-environment/tree/master/base-transformer-class)
* [x] provide recommendations for how it can be tested
* [x] provide one or more recommendations for each of Unit testing Functional testing frameworks

Also take notes on any changes to requirements, architecture, and implementation that you would recommend.

**Comment by kyclark** [comment]
* https://github.com/greenelab/continuous_analysis
* https://gist.github.com/julianpistorius/28950e4d60d194c198660ae843751b3b
* https://sci-f.github.io/spec-v1

Start with https://github.com/AgPipeline/drone-makeflow/tree/scif

Add some tests, then try to get SCIF test point, then explore hypothesis-based testing

**Comment by julianpistorius** [comment]
Have a look at Scientific Filesystem Container Builder:

- https://vsoch.github.io/2018/scientific-filesystem-builder/
- https://sci-f.github.io/builder/
- https://github.com/sci-f/builder

It handles the boring work (plumbing & automation) for us, meaning we can focus on creating scientifically relevant tests.

**Comment by julianpistorius** [comment]
@kyclark Check out the links to the Continuous Analysis paper: 

- https://greenelab.github.io/continuous_analysis/
- http://dx.doi.org/10.1101/056473

**Comment by dlebauer** [comment]
@kyclark flushed out some examples and made other recommendations in https://github.com/kyclark/configcode#configuration-and-testing-ideas-for-algorithm_rbgpy. 

@Chris-Schnaufer, @kyclark and I discussed these and decided on specific actions in this [hackmd](https://hackmd.io/UZPbVz1ISGKe4sFvmXHGNA).

Conclusion - @kyclark will start implementing tests using pytest along with a github action so that tests are run whenever a pull request is submitted. We never completed a full survey of testing tools - though there is a comprehensive [survey in the python wiki](https://wiki.python.org/moin/PythonTestingToolsTaxonomy) requested in this issue but I asked Ken to start with pytest at my insistence as a framework for unit testing because:

* pytest is widely used and robust 
* ken is very familiar with pytest and has already written a number of examples based on our code
* pytest has plugins for other suites that we reviewed and believe would / could be worthwile additions once the testing framework is setup, including
  * the [hypothesis pytest plugin](https://hypothesis.readthedocs.io/en/latest/details.html#the-hypothesis-pytest-plugin)   
  * support for [unittest testcase and fixtures](https://docs.pytest.org/en/3.0.1/unittest.html)

We didn't explicitly come to conclusions on the continuous integration / continuous analysis except that we will use github workflows / actions. Unless there is a reason not to use the scientific filesystem container builder, that seems like a natural fit given that we are using scif.
