### ISSUE TITLE
Develop integration tests for agpypeline library & use GitHub workflows

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#159]
**Task to do**
Provide a suite of integration tests for the installed python library files for the [agpypeline library](https://github.com/AgPipeline/agpypeline)

**Reason**
Integration testing will provide confidence in the code and catch potential errors

**Result**
There's a suite of integration tests that run over library code when things change

**Completion criteria**
- [ ] Integration testing suite for installed python files (if it's not installed it doesn't need testing; GitHub workflow supporting files, for example)
- [ ] GitHub workflow automatically runs the unit test when `master` and `develop` PR and pushes get made

**Comment by dlebauer** [comment]
@Chris-Schnaufer is this a duplicate of #158?

**Comment by Chris-Schnaufer** [comment]
@dlebauer They are not the same. The other is for Unit tests, this one is for integration tests: http://softwaretestingfundamentals.com/software-testing-levels/

**Comment by Chris-Schnaufer** [comment]
Chris to review this and update its status

**Comment by Chris-Schnaufer** [comment]
PR: https://github.com/AgPipeline/agpypeline/pull/13
