### ISSUE TITLE
Automate testing for Greenness indexes

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#181]
**Task to do**
Use GitHub workflows to automate existing tests for [Greenness indexes](https://github.com/AgPipeline/transformer-rgb-indices) 

**Reason**
Automate testing for code success

**Result**
Testing is automated

**Possible action to use**
https://github.com/marketplace?type=actions&query=pytest

**Comment by jvanderleeuw** [comment]
Based the tests off of https://github.com/kyclark/transformer-canopycover/blob/kyc_testing/canopycover_test.py 

Pull request: https://github.com/AgPipeline/transformer-rgb-indices/pull/7
