### ISSUE TITLE
Review PR template pull request

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#187]
**Task to do**
Review https://github.com/AgPipeline/.github/pull/6

**Reason**
Feedback is desired

**Result**
Changes are made to the PR, the linked issue is updated, and/or the changes are approved

**Comment by Chris-Schnaufer** [comment]
@dlebauer This has been set to Sprint 40 although the PR has already been merged. Did you intend for this to be for PR #8? In that case another issue is needed

**Comment by dlebauer** [comment]
will create another issue

**Comment by Chris-Schnaufer** [comment]
@dlebauer Closing this then
