### ISSUE TITLE
Make use of ArgParse in betydb2geojson.py

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#190]
**Task to do**
Update the drone_makeflow/betydb2geojson.py script to use ArgParse for parameter validation

**Reason**
ArgParse has better handling for arguments

**Result**
Better experience using the script

See https://github.com/AgPipeline/drone-makeflow/pull/3 for details on suggested ArgParse changes

**Comment by jvanderleeuw** [comment]
Github pull request: https://github.com/AgPipeline/drone-makeflow/pull/17
