### ISSUE TITLE
Review Seasons 4 and 6 SQLite databases

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#192]
**Task to do**

* [x] Review the two databases to see if changes need to be made

subtask of https://github.com/terraref/data-paper/issues/20

**Reason**
The databases are available for review. They need to be confirmed for containing the correct information.

**Result**
Either changes are suggested, or they databases can be considered OK

Season 4: https://drive.google.com/file/d/1eslWa5jP9HOY4sQULlEHcqSnZMCd9UUn/view?usp=sharing
Season 6: https://drive.google.com/file/d/10H4P5ZQNpWBNCtqkv8jUJelw_ZjIboi2/view?usp=sharing

**Comment by dlebauer** [comment]
These look good - I found a few inconsistencies and have moved these to a new issue https://github.com/az-digitalag/organization/issues/254. Priority depends on how difficult it will be to update a few of the fields.
