### ISSUE TITLE
Review SciF Canopy cover App in CyVerse DE

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#196]
**Task to do**
Review the working of SciF Canopy cover App in CyVerse DE by another user to ensure it's not tied to my environment

**Reason**
Checking that it appears to work correctly

**Result**

* [x] Confirmation that the DE app works
* [x] Document steps used

**Comment by dlebauer** [comment]
what sample data should I use?

**Comment by Chris-Schnaufer** [comment]
@dlebauer Any of the data folders I shared. The smallest set is: test_data/Canopy Cover App

**Comment by dlebauer** [comment]
* provide a quick summary and link to documentation in the app interface? 
  * point to sample-data folder and / or provide examples in the fields that list the files?
  * when the user clicks 'running' (or if they click 'completed' and presumably this link shows up elsewhere) it sends the user to ![image.png](https://images.zenhubusercontent.com/583f321cb9dc3c622022c169/42df7407-ae84-46b6-aea3-111ccf3fc0d4) but we have nothing under 'app manual'
* the DE App doesn't make it clear what the YAML should look like. 
  * we should revisit this. germplasmName should not be 'Sorghum bicolor' as that is the species, not the cultivar
  * shouldn't observationTimeStamp come from the image metadata?
  * can the entire yaml file be entered into a text box?

* canopycover.csv, canopycover_geostreams.csv should not show up in plot level folder (result.json is handy)
* add plot level *_rgb.tif files to plot level folders (this could be an optional flag)

**Comment by Chris-Schnaufer** [comment]
> provide a quick summary and link to documentation in the app interface

I can do that

> the DE App doesn't make it clear what the YAML should look like.

The YAML file requirement will become optional soon - I need to ensure it's not needed & that's handled correctly. I can add a link to the YAML definition to the DE UI: https://osf.io/xdkcy/wiki/Configuration%20YAML/
Also see: https://github.com/AgPipeline/issues-and-projects/issues/253

> shouldn't observationTimeStamp come from the image metadata

If the timestamp is not specified, it's retrieved from the available images and the earliest timestamp is used

> this should be handled by a separate workflow and only require the output of this

The current handling of shapefile, GeoJSON, and BETYbd is a convenience feature that will be converted into SciF apps
This is part of the rework in the following issue (because the workflows will need to be broken apart): https://github.com/AgPipeline/issues-and-projects/issues/227

**Comment by dlebauer** [comment]
where should I document the steps used? I began drafting them here: https://hackmd.io/EJtlqgGZSrKDZrpo64jh6Q but will need to update this when the app is updated

**Comment by Chris-Schnaufer** [comment]
I started an OSF page with the intent of adding the link to the App UI: https://osf.io/xdkcy/wiki/CyVerse%20Integration/

The broken link appears to be on the CyVerse side. The issue is being bumped up

**Comment by Chris-Schnaufer** [comment]
> add plot level *_rgb.tif files to plot level folders (this could be an optional flag)

In the newest app, this happens automatically now, no flag. The ability to control what's clipped is also part of the workflow re-work: #227

> canopycover.csv, canopycover_geostreams.csv should not show up in plot level folder

Adding issue for this: https://github.com/AgPipeline/issues-and-projects/issues/260. Given that at the time of this writing there's a `clean` feature that removes Makeflow generated files, this may not be needed
