### ISSUE TITLE
Failure to specify an input file should be an error for Transformers that work on files

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#205]
**The current behavior or issue**
Not specifying an input file for Transformers requiring one should be an error. Currently they don't report an error.

**The steps taken to reproduce the behavior or issue, or specify a location where the steps were recorded**
Run the Canopy Cover transformer code without an input file

**Expected behavior**
If no files are specified, an error should be reported via an exception. 

**Screenshots**
N/A

**Add other supporting information that may be useful**
N/A

**Completion criteria**
This is done when an error is reported if no files are specified on the transformer command line

**Comment by jvanderleeuw** [comment]
https://github.com/AgPipeline/agpypeline/pull/11
