### ISSUE TITLE
David to provide feedback on CyVerse FIELDimageR app

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#206]
**Task to do**
Use and provide feedback on CyVerse FIELDimageR app

**Reason**
Review to find improvements and test features

**Result**
The CyVerse FIELDimageR app is reviewed

**Comment by dlebauer** [comment]
This is fantastic = thanks for doing this. I think it is ready to be public and then we can let Fillipe know that it is available on VICE.

* is there documentation?
* would be nice to have a quick README ... at a minimum pointing to https://github.com/OpenDroneMap/FIELDimageR/blob/master/README.md
   * better to have something specific to VICE and use cases here?
   * or, could add the following to the FIELDimageR Dockerfile to render this locally (worth the effort?) I just worry that someone will open this and not know what is going on.
```
wget https://raw.githubusercontent.com/OpenDroneMap/FIELDimageR/master/README.md -o ~/README.md
r -e "rmarkdown::render('~/README.md')"
```
* need to make sure that username / password are clear in app documentation. 
* add `RUN installGithub.r andersst91/UAStools` to the VICE container specification? Would be nice to have (and promote) this alternative for generating shapefiles

**Comment by Chris-Schnaufer** [comment]
@dlebauer There's documentation for exporting plots at https://github.com/Chris-Schnaufer/rstudio-FIELDimageR and the original at https://github.com/OpenDroneMap/FIELDimageR/blob/master/README.md (as you noted). 

I will look into making the additions you're suggesting

**Comment by Chris-Schnaufer** [comment]
I created an issue for the following suggestion
> add RUN installGithub.r andersst91/UAStools to the VICE container specification? Would be nice to have (and promote) this alternative for generating shapefiles


https://app.zenhub.com/workspaces/ua-ag-data-science-5a57a3198339f11ba1c85775/issues/agpipeline/issues-and-projects/208

**Comment by Chris-Schnaufer** [comment]
I am unable to get the README into a running container on VICE - it's available in the Docker image but not when running. I have added links to the documentation in the VICE app I created.

Made suggested documentation changes
