### ISSUE TITLE
Return code from Transformers doesn't match specified return code

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#207]
**The current behavior or issue**
The return code specified in the returned JSON should be the return code from the Transformers. The "application" should return the specified code to the caller

**The steps taken to reproduce the behavior or issue, or specify a location where the steps were recorded**
Run a transformer with no parameters. An error code will be reported in the return JSON but the app return code is zero (0)

**Expected behavior**
The return code and the code in the returned JSON match

**Screenshots**
N/A

**Add other supporting information that may be useful**
N/A

**Completion criteria**
When the return codes match

**Comment by jvanderleeuw** [comment]
Pull request: https://github.com/AgPipeline/transformer-canopycover/pull/21
