### ISSUE TITLE
Have CyVerse Canopy Cover write to single CSV files instead of into each plot folder

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#210]
**Task to do**
Have a CSV files contain all plots values

**Reason**
Scattered CSV files makes it hard to bring them into one place when not using automation

**Result**
For any run of CanopyCover all plot data is contained within one top-level plot file and not in each plot folder

**Comment by dlebauer** [comment]
Is this CyVerse specific or can this be a general functionality that also works in CyVerse? Having all of the results will also be useful for those using the command line and other workflow systems.

**Comment by Chris-Schnaufer** [comment]
This is for CyVerse always, and is available as an app to the rest of the SciF docker image users. The CyVerse solution runs this app to do the work

**Comment by Chris-Schnaufer** [comment]
PR: https://github.com/AgPipeline/drone-makeflow/pull/10
