### ISSUE TITLE
Make a determination on SciF writing a makeflow JSON file vs. having user specify

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#214]
**Task to do**
Decide if we want users to generate a JSON file used by Makeflow as opposed to having the SciF workflow generate one. See https://github.com/AgPipeline/drone-makeflow/pull/3#discussion_r461069305

**Reason**
There's a difference in opinion as to whether to do this

**Result**
We keep it as-is, or change to have the user generate the file. If a change is needed, an issue will be created

**Comment by julianpistorius** [comment]
This is tangentially related to this comment: https://github.com/AgPipeline/drone-makeflow/pull/4#discussion_r467255848

> There is a further simplification which I would really like, which is to not have SCIF entrypoints for each different workflow. 
> 
> Instead we would expose a single `makeflow` app in the container. Then we can have shell scripts (inside and/or outside the container) for each different workflow which call the `makeflow` entrypoint with different parameters. 
> 
> Another benefit is that a container like this becomes less like an appliance and more like a toolbox. As a result a user can create & test their own workflows easily.

**Comment by Chris-Schnaufer** [comment]
This is obsolete in that a makeflow specific file containing parameters is needed.
