### ISSUE TITLE
Investigate the use of Hypothesis for enhancing our testing

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#228]
**Task to do**
Determine if Hypothesis is a useful addition to our automated testing

**Reason**
Aside from testing available from `pytest` there are other tools that may help with testing. Investigating Hypothesis is one of them.

**Result**
Make a determination if Hypothesis is a good tool to use

**Comment by dlebauer** [comment]
great idea, but closing for now due to lack of interest / demand
