### ISSUE TITLE
I would like to not have SCIF entrypoints for each different workflow

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/computing-pipeline#232]
**Please describe your request. Is your feature request related to a problem?**

- It clutters the number of SCIF apps
- Duplicated, error-prone logic in the `apprun` sections

**Describe the solution you'd like**

Having a single `makeflow` app in the SCIF container means it becomes less like an appliance and more like a toolbox. As a result a user can create & test their own workflows easily.

**Describe alternatives you've considered**

- Nothing yet.

**Additional context**

We could expose a single `makeflow` app in the container. Then we can have shell scripts (inside and/or outside the container) for each different workflow which call the `makeflow` entrypoint with different parameters. 

**Related***

- https://github.com/AgPipeline/issues-and-projects/issues/217
- https://github.com/AgPipeline/issues-and-projects/issues/214

**Comment by Chris-Schnaufer** [comment]
Closing as obsolete. Scif re-work makes workflows external to the system
