### ISSUE TITLE
Add stronger typing to AgPypeline Library

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#236]
**Task to do**
Add stronger typing to library along the lines of recommendation https://github.com/kyclark/transformer-canopycover/blob/kyc_testing/REVIEW.adoc (search for 'class CheckMD(NamedTuple)')

Stronger typing is needed when data is retrieved or returned from outside of the library. For example, after validating a JSON file's contents any functions residing within the library that aren't exposed* don't need strong typing.

*Refer to the Python specifications for how to declare that a function, class, etc is not intended to be used outside of a module/file. Note that this doesn't prevent it from being used from the outside, just that it's not designed for that.

**Reason**
Catch bad data before it can present a problem and issue a meaningful warning or error.

**Result**
Stronger typing is enforced with outside data at designated entry points.

**Comment by dlebauer** [comment]
what is the status of this work?

**Comment by Chris-Schnaufer** [comment]
It has been merged into the develop branch: https://github.com/AgPipeline/agpypeline/tree/develop/agpypeline.

Waiting for review before merging into main branch: https://github.com/AgPipeline/agpypeline/pull/27
