### ISSUE TITLE
Add Mypy testing to AgPypeline GitHub workflows

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#237]
**Task to do**
Add Mypy testing to merge- and PR-based workflows as another test for code quality

**Reason**
Better code benefits

**Result**
A new workflow (grid or separate yaml file) using Mypy is enabled

**Comment by Chris-Schnaufer** [comment]
Also see additional comments on this topic: https://github.com/AgPipeline/transformer-plotclip/pull/27#issuecomment-727621707 (please ignore non-code quality comments)

**Comment by julianpistorius** [comment]
@Chris-Schnaufer I assigned this issue to you because I need you to review and merge the following two PRs:

- https://github.com/AgPipeline/Organization-info/pull/10
- https://github.com/AgPipeline/transformer-plotclip/pull/42
