### ISSUE TITLE
Add ability to monitor progress of SciF workflows

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#243]
**Task to do**
Add the ability to monitor the process of the SciF workflows

**Reason**
From PR: https://github.com/AgPipeline/drone-makeflow/pull/4#discussion_r470144596
`Wish list: A command to monitor the progress`

**Result**
Ability to monitor progress of Workflow, including useful status updates and error messages.

**Comment by Chris-Schnaufer** [comment]
@julianpistorius Do you have a suggestion for how you would like this done (technology-wise)?

**Comment by julianpistorius** [comment]
I'd like to use the built-in Makeflow monitoring:

https://cctools.readthedocs.io/en/latest/makeflow/#monitoring

**Comment by Chris-Schnaufer** [comment]
Following Julians suggestion, there is a need to document these existing monitoring tools for our environment (namely tying in the tools with the makeflow artifacts documentation).

**Comment by Chris-Schnaufer** [comment]
PR: https://github.com/AgPipeline/drone-makeflow/pull/24
