### ISSUE TITLE
I would like to request sensible rounding for all extractors

### ISSUE THREAD

**Issue by dlebauer** [AgPipeline/computing-pipeline#262]
**Please describe your request. Is your feature request related to a problem?**

Currently e.g. canopy cover results have arbitrary level of precision, e.g. 64.40907821786126% canopy cover. For this measurement it can be rounded to the nearest whole number. 

**Describe the solution you'd like**

* [ ] sensible rounding by default for plot-level phenotypes. Three significant digits is a sensible default (e.g. 64.4 or 6.44 or 0.644)
* [ ] a test that no extractor allows more than 5 significant digits (if this becomes necessary for a particular extractor this can be revisited)

**Comment by Chris-Schnaufer** [comment]
Closing as obsolete. Replaced by https://github.com/AgPipeline/issues-and-projects/issues/342
