### ISSUE TITLE
Create user story and outline plan for developing algorithm 

### ISSUE THREAD

**Issue by MagicMilly** [AgPipeline/computing-pipeline#275]
**Document all planning, steps taken, questions, and suggestions throughout project**

- [x] Write user story
- [x] Read documentation on getting started
- [x] Outline plan for developing algorithm, using documentation as guide

@Chris-Schnaufer feel free to comment with suggestions or particular requests

**Comment by MagicMilly** [comment]
Existing HackMD [notes](https://hackmd.io/@eywX1MatRnyBtYFBB3Gqwg/HkIAu2QOP), which I've asked for feedback on  ticket #339. Follow-up action ticket #340

**Comment by Chris-Schnaufer** [comment]
@MagicMilly Can this be closed?
