### ISSUE TITLE
Test fieldimageR on CyVerse

### ISSUE THREAD

**Issue by MagicMilly** [AgPipeline/computing-pipeline#341]
- [x] Review tutorial in README of the fieldimager docker repository https://github.com/AgPipeline/rstudio-FIELDimageR
- [ ] Provide feedback / suggest edits
  - [ ] reorganize / revise for clarity
  - [ ] add pre-requisites
  - [ ] make sure objectives of this readme are clearly stated (to generate geojson? can it also generate shp files?), 
  - [ ] reference the fieldimager readme for more information
- [ ] report bug with uploading to CyVerse

**Comment by MagicMilly** [comment]
@Chris-Schnaufer I'm stuck in the zone of loading the sample image `EX1_RGB.tif` in the **Preparation Steps** of the README. I was able to load the specified libraries in the RStudio VICE app (v 3.6.3), but when I run this command:
```
EX1<-stack("EX1_RGB.tif")
```
I get this error:
```
Error in .local(.Object, ...) : 

Error in .rasterObjectFromFile(x, objecttype = "RasterBrick", ...) : 
  Cannot create a RasterLayer object from this file. (file does not exist)
```
I'm not sure how to load this file so that it can be used for the example tutorial. 

- Is it already included somewhere, like a specific repo or working directory?
- Should it be downloaded from the Google Drive [link](https://drive.google.com/file/d/1S9MyX12De94swjtDuEXMZKhIIHbXkXKt/view) that was provided and saved locally?
- Should it be loaded to CyVerse and then added as a `Source` file before launching the app?
- Or, am I completely off base with this line of questioning, and should I have gone through all the local installation steps in the OpenDroneMap/FIELDimageR [repo](https://github.com/OpenDroneMap/FIELDimageR) first?

**Comment by dlebauer** [comment]
The instructions should be more explicit about where that tif file comes from. 

Probably need to update instructions so that a user can upload their data. They can do this by using the upload button on the files tab in the lower right of Rstudio 

![image.png](https://images.zenhubusercontent.com/583f321cb9dc3c622022c169/1b226501-b31c-484c-b3f6-c982c891140f)

**Comment by Chris-Schnaufer** [comment]
@MagicMilly What TIFF file do you have available to you on the instance? You can specify a folder containing a/the TIFF file(s) when launching the app. That will then be available to you when you are in RStudio. You would need to replace the EX1_RGB.tif with the name of a file to process

@dlebauer I agree about upload. It's also possible to mount volumes to the running docker image so that an upload isn't required.

**Comment by MagicMilly** [comment]
### Uploading the sample file

I wasn't able to upload any files using the button from David's screenshot. I tried this
<img width="379" alt="Screen Shot 2020-11-19 at 10 39 56 AM" src="https://user-images.githubusercontent.com/34486154/99706595-87470800-2a58-11eb-9878-cdf4a7c84b86.png">
and received this error
<img width="383" alt="Screen Shot 2020-11-19 at 10 39 46 AM" src="https://user-images.githubusercontent.com/34486154/99706638-962dba80-2a58-11eb-9067-6420b3e0289a.png">
But I was able to specify a source _folder_ (but not one file) when I launched the app, after uploading it to the DE myself.

### Cropping and Rotating

Another question I have is, are the images generated from the cropped TIF file supposed to be exactly vertical? After running this command
```
EX1.Crop <- fieldCrop(mosaic = EX1)
```
I selected four points, which produced this output
<img width="640" alt="Screen Shot 2020-11-19 at 11 22 58 AM" src="https://user-images.githubusercontent.com/34486154/99707465-b3af5400-2a59-11eb-8f30-ed9cc1dda1f6.png">
I ran the next command
```
EX1.Rotated<-fieldRotate(mosaic = EX1.Crop, clockwise = F)
```
which produced this output
<img width="643" alt="Screen Shot 2020-11-19 at 11 28 28 AM" src="https://user-images.githubusercontent.com/34486154/99707949-654e8500-2a5a-11eb-9ccb-cb183e20d19a.png">
and the prompt to `[1] "Select 2 points from left to right on image in the plots space. Use any horizontal line in the field trial of interest as a reference."` If I select 2 points that would be horizontal in the field, it produces this image 
<img width="641" alt="Screen Shot 2020-11-19 at 11 33 29 AM" src="https://user-images.githubusercontent.com/34486154/99708480-1ce39700-2a5b-11eb-9201-daf7eb82eb66.png">
with this message
```
[1] "Theta rotation: 86.479"
```
So is it correct to assume that if the cropped image is already vertically aligned, you should _not_ run the provided command to rotate, but something different to make the rows _perfectly_ vertically aligned? These may not be questions that somebody who is already familiar with drone images and these types of files would have.

**Comment by Chris-Schnaufer** [comment]
@MagicMilly Did you reference the original documentation at https://github.com/OpenDroneMap/FIELDimageR#2-selecting-the-targeted-field-from-the-original-image? Perhaps we can have a Zoom session?

**Comment by MagicMilly** [comment]
No I had not, but that looks like it has all the answers to my question(s). Thank you!

**Comment by MagicMilly** [comment]
Will submit edited README as a PR work-in-progress today. HackMD notes are [here](https://hackmd.io/@eywX1MatRnyBtYFBB3Gqwg/BkCYNOWqw), though much of my suggested changes will be different now that I have a better understanding of the separate instructions, thanks to @Chris-Schnaufer! 

note: my comments are at the bottom of the HackMD

**Comment by MagicMilly** [comment]
I have made some changes to the README in my own [repo](https://github.com/MagicMilly/rstudio-FIELDimageR). I think the most important change should be to separate the beginning instructions for using the CyVerse app vs. the instructions for developers/those who want to work on their local machine. Then there can be a link in each section to the clipping instructions once you're in RStudio. Some of the instructions for developers - like to load certain R libraries - should be removed from the instructions for using the app. 

Most users who are unfamiliar with CyVerse get confused/frustrated easily, so those instructions should be clear, starting with signing up for an account, in addition to some screenshots when describing how to use the app. Even with detailed instructions, though, I have not had much success in getting new users to utilize the CyVerse DE. 

The instructions should also be explicit when describing what kind of input files can be used, and how to actually use them within the app (by starting with adding them to the DE, and then as a source for the app). The example tif file doesn't really answer a question like, "But how do I use this app with _my_ drone images?"

The prerequisites for most users is to read the original instructions on OpenDroneMap before starting to work in RStudio. Other prerequisites like familiarity with Docker should be moved to the delineated Developer section.

**Comment by Chris-Schnaufer** [comment]
@MagicMilly Based upon what you wrote, should the focus be on non-DE (placed at the beginning of the document)?

**Comment by MagicMilly** [comment]
I think the DE will still be way easier for most users. Oh, a note that encourages the use of CyVerse support would be useful! Then they will know what to do when/if they get blocked and will hopefully feel less intimidated using it. 🎉
