### ISSUE TITLE
Metadata and output errors to fix

### ISSUE THREAD

**Issue by dlebauer** [AgPipeline/computing-pipeline#342]
After running the canopy cover app in DE, I found the following that should be changed

* [x] Outputs should be truncated to 3 significant digits (not three decimal places, but, e.g. 65.5 or 0.655)
* [x] citation_author, citation_title, citation_author fields refers to the extractor but not to the output. This should be set in experiment.yaml and will be different for each user / experiment (see comment below for follow up)
* [x] canopycover_geostreams.csv files are not needed
* [ ] ~plot level (image and mask) clips should have plot names in them? or somehow be distinct from full field(?)~
* [x] local_datetime should be date / time of image capture, not date / time of ortho creation or date / time at which the workflow was run. Could come from image metadata or be required in metadata.yaml (See comment below for follow up)

**Comment by Chris-Schnaufer** [comment]
Re: local_timestamp, replace no timestamp with an empty field
Re: citation fields - place in Makeflow JSON file - there is a way to do this after breaking apart workflows

**Comment by Chris-Schnaufer** [comment]
@dlebauer What is the problem that would be resolved by changing the clipped names to include plot names? Thanks

**Comment by dlebauer** [comment]
> What is the problem that would be resolved by changing the clipped names to include plot names? Thanks

1. Downloading a bunch of files that have the same name
2. having the same name in the full ortho as in the plot clips

But note that ... I added a "?" because I wasn't sure if this was a good idea or necessary. Directory structure takes care of this, but when I was checking out the files I was downloading them one at a time and ran into the problem of having duplicate names.

**Comment by Chris-Schnaufer** [comment]
Thanks @dlebauer. I did notice the "?". I am/was trying to get the specifics as to what was encountered. If you are OK with bumping this specific change to a lower priority - since it's encountered only encountered in a download situation, and only when downloading individual files (as opposed to folders) - I would like to create a new issue for this and defer a possible change to a later time.

**Comment by dlebauer** [comment]
yes, feel free to bump. Definitely a lower priority
