### ISSUE TITLE
Different output when running agpypeline tests from Mac python terminal and bash python via ubuntu 18.04

### ISSUE THREAD

**Issue by jvanderleeuw** [AgPipeline/computing-pipeline#344]
There is different output produced when running test_geometries_convert_geometry_from_polygon() from a local (Mac) python terminal versus when running it from a bash python terminal such as that which is run on a GitHub workflow. 

More specifically, when new_geom.Transform(transform) is called in convert_geometry, the result is different for the different python terminals. The coordinates appear in different positions and the coordinates in the bash python terminal result which are near zero are not rounded. Below is the test function

def test_geometries_convert_geometry_from_polygon():
    """Tests convert_geometry by checking the function call on geometries
    created from ogr.Geometry and spatial references created from
    osr.SpatialReference against a file containing function call results"""
    check_result = json.load(open("data/convert_geometry_from_polygon.json", 'r'))
    ring = ogr.Geometry(ogr.wkbLinearRing)
    ring.AddPoint(1, 0)
    ring.AddPoint(0, 1)
    ring.AddPoint(-1, 0)
    ring.AddPoint(0, -1)
    poly = ogr.Geometry(ogr.wkbPolygon)
    poly.AddGeometry(ring)
    source = osr.SpatialReference()
    source.ImportFromEPSG(4326)
    poly.AssignSpatialReference(source)
    result = geometries.convert_geometry(poly, source)
    assert check_result["same_epsg"] == str(result)
    source2 = osr.SpatialReference()
    source2.ImportFromEPSG(3857)
    result2 = geometries.convert_geometry(poly, source2)
    assert check_result["different_epsg"] == str(result2)

The first image is the Mac terminal output and the second is the bash terminal output:

![Screen Shot 2020-11-04 at 3.51.11 PM.png](https://images.zenhubusercontent.com/5e6fa9f130bce8c17ee4d226/28d86f48-349e-48be-ac83-c27b30f5a108)

![Screen Shot 2020-11-04 at 4.03.03 PM.png](https://images.zenhubusercontent.com/5e6fa9f130bce8c17ee4d226/05944a8a-10d0-478b-aba8-d6cf1790b05a)

**Comment by Chris-Schnaufer** [comment]
The order of X,Y,Z values was changed in latest OGR libraries. This is taken care of with AgPypeline PR: https://github.com/AgPipeline/agpypeline/pull/13
