### ISSUE TITLE
Process Rosa's (YCEDA) data 

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#347]
**Task to do**
Demonstrate processing of YCEDA data for Fall of 2020 provided by Rosa

**Reason**
Demonstrate the ability to use Drone workflow to obtain meaningful results

**Result**
At least two day's data processed and presented to Rosa

**Comment by Chris-Schnaufer** [comment]
Processed 21-10-2020 and 30-10-2020 Fields 3, 4, 9, 10. Waiting on Iceberg lettuce field coordinates

**Comment by dlebauer** [comment]
Looks great so far. I've written out some feedback on the first iteration. 

First, the highest priority would be to provide Andy with one CSV file (perhaps one csv file per field?) that contains canopy cover for all dates (and optionally all fields).

I've put additional notes [in this hackmd](https://hackmd.io/Bbe_POvwQN6uN18jCDlugA), but these mostly shouldn't delay getting results to Andy so may warrant new issues:

**Comment by Chris-Schnaufer** [comment]
The following tag implements per-plot YAML for species: https://github.com/AgPipeline/transformer-canopycover/tree/v1.4

**Comment by Chris-Schnaufer** [comment]
The remaining issues from the HackMD notes are:
- https://github.com/AgPipeline/issues-and-projects/issues/360
- https://github.com/AgPipeline/issues-and-projects/issues/361
