### ISSUE TITLE
Continue working through DPP as a new user with sample data

### ISSUE THREAD

**Issue by MagicMilly** [AgPipeline/computing-pipeline#349]
As a follow-up and breakdown of issue #340:

- [ ] Get Rosa's sample data from Chris 
- [ ] Run plot clip and canopy cover using scif / docker on the command line
    - [ ] make sure this process is documented. 
            - where are current docs? are they easy to find? Are they where they should be?
            - completion is if you have a single page you could point Rosa to that describes how she can run the analysis 

Taking notes here: https://hackmd.io/@eywX1MatRnyBtYFBB3Gqwg/SJOAyLB9D

**Comment by dlebauer** [comment]
What could make the docker commands less intimidating, e.g. would it be possible to replace 

```
docker run --rm --mount "src=${PWD}/test_data,target=/mnt,type=bind" agdrone/transformer-soilmask:2.1 --working_space "/mnt" --metadata "/mnt/experiment.yaml" "/mnt/2020-11-06_smithfield_50ft_transparent_mosaic_group1.tif"
```

with

```
soilmask.sh myortho.tif
```

(is the experiment.yaml required for the soilmask? or, could it be assumed to exist by default?)

**Comment by dlebauer** [comment]
For Rosa, the focus can be on the CyVerse interface; skip the docker stuff for her use case

**Comment by Chris-Schnaufer** [comment]
Chris to review notes.

**Comment by Chris-Schnaufer** [comment]
Post-review of notes:
As has been mentioned elsewhere in documentation related issues, it is very difficult to know where to start at. The starting point is actually the drone-makeflow docker image (or repository, if wanting to build your own docker image). There is also a CyVerse app that performs the processing with a much reduced interface (specify 3 files: TIFF, experiment information, and plot geometries) - not requiring explicit docker/docker-related commands.

**Comment by dlebauer** [comment]
Although it hasn't been written up, I made a (silent) youtube video that I
made of the DE interface https://youtu.be/oQLyO8sK2Ys

**Comment by MagicMilly** [comment]
Updates on my work are in issue #341
