### ISSUE TITLE
Discuss removal of "self" from plotclip class method instances

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#357]
**Task to do**
See https://github.com/AgPipeline/transformer-plotclip/pull/27#issuecomment-727621707 - ignore comments not related to the use of `self` in class method signatures

> Unnecessary use of classes

> We would need to discuss this: for example, why a class is used, and how to resolve same-named class-method signatures that would require `self1` in some instances and not in others.

**Reason**
Resolve the approach to take

**Result**
Consensus on how to approach this problem

**Comment by dlebauer** [comment]
@Chris-Schnaufer and @julianpistorius is this still relevant?
