### ISSUE TITLE
Investigate using SonarCloud as part of code quality checks

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#358]
**Task to do**
Investigate use of SonarCloud as part of CI (Continuous Integration)

**Reason**
Another code quality check that we may want to implement

**Result**
Determination made for include SonarCloud as part of CI
- if to be included, new issues written up to implement, or,
- if it is not to be used, document why

See https://sonarcloud.io/

**Comment by Chris-Schnaufer** [comment]
@julianpistorius What does this add that the other code checking tests don't?

**Comment by julianpistorius** [comment]
It's a dashboard that:

- Shows how metrics change over time (instead of a snapshot in time)
- Includes metrics like 'maintainability'
- Can be used to enforce quality gate checks (fail a PR which lowers code coverage by more than x%)

**Comment by julianpistorius** [comment]
@Chris-Schnaufer - What would you like me to do next on this?
