### ISSUE TITLE
Canopy cover seems to miss quite a bit of lettuce early in the season

### ISSUE THREAD

**Issue by dlebauer** [AgPipeline/computing-pipeline#362]
It appears that the lettuce are mostly masked on the 19th and 30th, e.g.
![image](https://user-images.githubusercontent.com/464871/99861642-f05f7600-2b53-11eb-94c1-657ae9e4e8ba.png)

**Comment by Chris-Schnaufer** [comment]
@dlebauer This appears to be feature of the soil masking algorithm. Looking at TERRAREF data for 2019-12-04 vs 2019-12-26 (not the same part of the field) I notice that the column (row) of plants is very irregular for the earlier date but is regular for the later date, indicating to me that (for this example) there are plants being missed earlier in the season. While this is not conclusive, the base of the plants are also missing which I feel also points to the algorithm. I was not able to find the original RGB images, per masked, to compare against. I am going to attempt to process the RAW files to see if I can re-generate the RGB images for comparison.

![Screen Shot 2020-11-23 at 1.01.57 PM.png](https://images.zenhubusercontent.com/5c14118eee1e975f1842e1c2/0d21b2ed-a1ac-41fc-bc83-0790d9a4799f)
![Screen Shot 2020-11-23 at 1.02.13 PM.png](https://images.zenhubusercontent.com/5c14118eee1e975f1842e1c2/bc875f80-0880-4ae9-b4a4-c8047960811d)

**Comment by Chris-Schnaufer** [comment]
I am not having any luck generating a source RGB (unmasked) file

**Comment by dlebauer** [comment]
> I am not having any luck generating a source RGB (unmasked) file

Not sure what this means? Aren't these the source files that Rosa sent?

It might be worth having a new masking option that 1) generates a histogram of green/red ratio and 2) allows the user to set a threshold based on the per pixel Green/Red ratio. Andy mentioned this in his email.

**Comment by Chris-Schnaufer** [comment]
@dlebauer 

> Not sure what this means?

See my above comment about trying out TERRAREF RAW file to soil-masked TIFF

I did get a reply from Max regarding why the error was occurring - I didn't follow the naming convention: https://terra-ref.slack.com/archives/C4VQYUNA1/p1606399294003300

**Comment by Chris-Schnaufer** [comment]
Next steps are:
1) Check with PhytoOracle to see if this was resolved for that project
2) and/or explore simple masking algorithm and implement if it works: green/red ratio and using a threshold of 1.0

**Comment by Chris-Schnaufer** [comment]
From Emmanuel on Slack: `Regarding the lettuce masking, we have taken a different approach. We are using a Faster R-CNN detection network to locate the plants, we use the model's bounding box predictions to then focus on specific areas where we then do some thresholding to determine the area. This is working quite well for our lettuce data.`

The code repository that detects the plants is: https://github.com/phytooracle/rgb_flir_plant_detection
The soil mask repository only works with 3D data: https://github.com/phytooracle/3d_soil_mask

**Comment by Chris-Schnaufer** [comment]
Writing a new issue to implement Andrew French's soil mask algorithm & to use that as a test case for writing new transformer.

https://github.com/AgPipeline/issues-and-projects/issues/370
