### ISSUE TITLE
Create a test cases for new extractor template

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#4]
**Task to do**
Create unit and functional tests for the non-docker-image and docker-image template

**Reason**
Preparation for integrating with TravisCI

**Result**
A fully tested extractor template

**Comment by Chris-Schnaufer** [comment]
@Sithyphus Put a link to test repo here

**Comment by Sithyphus** [comment]
https://github.com/AgPipeline/base-docker-support/tree/test-development/base-image
