### ISSUE TITLE
Integrate extractor template with TravisCI

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#5]
**Task to do**
After tests are built, integrate with TravisCI

**Reason**
Able to automatically test changes to extractor template

**Result**
Full integration with TravisCI and ability to make Pull Requests dependent upon successful CI runs

**Comment by Chris-Schnaufer** [comment]
Integrate test cases remains

**Comment by Sithyphus** [comment]
Completed .yml.travis file
https://github.com/AgPipeline/base-docker-support/blob/test-development/.travis.yml

and completed a build run
![2019-11-12 13_03_25-AgPipeline_base-docker-support - Travis CI.png](https://images.zenhubusercontent.com/5dadfa4f58cac1000181cf89/600249f8-7ed6-4c34-af26-a0075afae9a3)

![2019-11-12 13_09_50-AgPipeline_base-docker-support - Travis CI.png](https://images.zenhubusercontent.com/5dadfa4f58cac1000181cf89/2f0637db-df1d-4932-aac9-30625e9aa518)

There are some test failures that need to be worked out but basically the system is working as intended. I'll need to make another ticket for fixing whatever's broken.
