### ISSUE TITLE
Review Jorge's PRs

### ISSUE THREAD

**Issue by Sithyphus** [AgPipeline/computing-pipeline#94]
Make sure to review (and eventually merge) the following pull requests
- [x] https://github.com/AgPipeline/transformer-ply2las/pull/5
- [x] https://github.com/AgPipeline/template-lidar-plot/pull/1
- [x] https://github.com/AgPipeline/AgPipeline.github.io/pull/3
- [x] https://github.com/AgPipeline/ua-gantry-environment/pull/9

**Comment by Chris-Schnaufer** [comment]
The PRs are either merged, or cancelled with tickets written for additional work that needs to be done
